### PR TITLE
[MCC-620147] : mauth-proxy changes to work with POST and PATCH

### PR DESCRIPTION
**Pull request by nsingh-mdsol**
This PR includes the changes:
  1. refactor mauth-proxy to accept POST and PATCH request. (it was failing with 
                 java.lang.UnsupportedOperationException: direct buffer at com.mdsol.mauth.proxy.MAuthHttpRequestSigner.signRequest(MAuthHttpRequestSigner.java:28)
  2. update the tests

### CODE REVIEW

**Comment by jatcwang** [comment]
FYI you can now use https://github.com/mdsol/mauth-insomnia-plugin instead of mauth-proxy. The littleproxy library is no longer maintained which means we'll eventually have to remove it.

**Comment by nsingh-mdsol** [comment]
Does this mean I should close this PR and start using `mauth-insomnia-plugin`?

**Comment by jatcwang** [comment]
@nsingh-mdsol Can try and get this merged in case anyone else wants to use it, but if the insomnia plugin solves your problem then that's the better way forward

**Comment by nsingh-mdsol** [comment]
@austek, addressed the comments. could you please re-look when you have a minute?

**Pull request merged**
